User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> python3.7 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> pyenv root
> conda info --json
> pyenv root
Python interpreter path: /usr/bin/python3
Error 2021-06-10 08:36:31: Failed to check if file needs to be fixed EntryNotFound (FileSystemError): Unable to read file '/root/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file '/root/.config/Code/User/settings.json')
    at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at y.readText (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:344717)
    at p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:581560)
    at /root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580687
    at async Promise.all (index 0)
    at p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580633)
    at p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580260) {
  code: 'FileNotFound'
}
Error 2021-06-10 08:36:31: Failed to check if file needs to be fixed EntryNotFound (FileSystemError): Unable to read file '/home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask/.vscode/settings.json')
    at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at y.readText (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:344717)
    at p.doesFileNeedToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:581560)
    at /root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580687
    at async Promise.all (index 1)
    at p.getFilesToBeFixed (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580633)
    at p.updateTestSettings (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:580260) {
  code: 'FileNotFound'
}
> pyenv root
Starting Pylance language server.
Error 2021-06-10 08:36:31: Failed to start language server, Class name = r, completed in 1ms, has a falsy return value, Arg 1: <Uri:/home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask/app.py>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, May 27 2021, 13:30:53) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"1d9c88c10d3230b5e2f19dfa759b5ee346d0b760a4b5a2837b3f21b4fffacdf4403a06492f74ae42113a3c21cfa67a49746b55be681bd3a2cc1a334a369733db","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit","store":true}, Return Value: undefined Error: ms-python.vscode-pylance not installed
    at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:233011)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at r.start (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:239427)
Error 2021-06-10 08:36:31: Error: ms-python.vscode-pylance not installed
    at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:233011)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at r.start (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:239427)
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-10 08:36:31: Failed to activate language server, Class name = a, completed in 6ms, has a falsy return value, Arg 1: <Uri:/home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask/app.py>, Arg 2: {"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, May 27 2021, 13:30:53) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"1d9c88c10d3230b5e2f19dfa759b5ee346d0b760a4b5a2837b3f21b4fffacdf4403a06492f74ae42113a3c21cfa67a49746b55be681bd3a2cc1a334a369733db","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit","store":true}, Return Value: undefined Error: ms-python.vscode-pylance not installed
    at d.getCurrentLanguageServerDirectory (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:233011)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at r.start (/root/.vscode/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:239427)
> pyenv root
> pyenv root
> conda --version
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /home/chayut/Downloads/Git/face_recognition_attend/Testing/face_recognition/face_rec_flask
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py
Error 2021-06-10 08:36:32: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:584: DeprecationWarning: Use the code keyword argument instead.
  jedi.Script(

Error 2021-06-10 08:36:32: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Use the code keyword argument instead.
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2021-06-10 08:36:32: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:105: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
  call_signatures = script.call_signatures()

Error 2021-06-10 08:36:32: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:230: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
  completions = script.completions()

Error 2021-06-10 08:37:21: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-06-10 08:37:24: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:144: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
  call_signatures = script.call_signatures()

Error 2021-06-10 08:47:44: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:601: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).goto instead.
  script.goto_assignments(follow_imports=True), request["id"]

Error 2021-06-10 08:49:13: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-06-10 08:49:51: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Use the code keyword argument instead.
  script = jedi.Script(

Error 2021-06-10 08:49:51: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:584: DeprecationWarning: Use the code keyword argument instead.
  jedi.Script(

Error 2021-06-10 08:50:11: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2021-06-10 08:50:11: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-06-10 08:51:07: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:601: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).goto instead.
  script.goto_assignments(follow_imports=True), request["id"]

Error 2021-06-10 08:51:10: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:584: DeprecationWarning: Use the code keyword argument instead.
  jedi.Script(

Error 2021-06-10 08:51:11: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:590: DeprecationWarning: Use the code keyword argument instead.
  script = jedi.Script(
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:105: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
  call_signatures = script.call_signatures()
/root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:230: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
  completions = script.completions()

Error 2021-06-10 08:51:18: stderr jediProxy Error (stderr) /root/.vscode/extensions/ms-python.python-2021.5.842923320/pythonFiles/completion.py:144: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
  call_signatures = script.call_signatures()

